<?php
/**
 * This file is part of the pushover package.
 *
 * (c) Massimo Naccari "maxowar"
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */


namespace Pushover\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Symfony\Component\Console\Style\SymfonyStyle;

class InstallCommand extends Command
{
    public function configure()
    {
        $this->setName('pushover:install');
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $style = new SymfonyStyle($input, $output);
        $style->title("Pushover install");

        $token = $style->ask("Token");
        $user = $style->ask("User");
        $path = $style->ask("Save path", getcwd());

        $php = <<< EOF
<?php

/**
 * generated by pushover:install
 */

define('PUSHOVER_APP_TOKEN', "$token");
define('PUSHOVER_USER_KEY', "$user");

EOF;
        file_put_contents($path . DIRECTORY_SEPARATOR . ".pushover", $php);

        $style->success("Configuration saved to " . $path . DIRECTORY_SEPARATOR . ".pushover");
    }
}